# Generated by Django 5.0.6 on 2024-06-25 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DayWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.IntegerField(choices=[(1, 'AC'), (2, 'AL'), (3, 'AP'), (4, 'AM'), (5, 'BA'), (6, 'CE'), (7, 'DF'), (8, 'ES'), (9, 'GO'), (10, 'MA'), (11, 'MS'), (12, 'MT'), (13, 'MG'), (14, 'PA'), (15, 'PB'), (16, 'PE'), (17, 'PI'), (18, 'PR'), (19, 'RJ'), (20, 'RN'), (21, 'RO'), (22, 'RR'), (23, 'RS'), (24, 'SC'), (25, 'SE'), (26, 'SP'), (27, 'TO')], default=27)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('open_time', models.TimeField(blank=True)),
                ('close_time', models.TimeField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('latidude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='business.category')),
                ('days_week', models.ManyToManyField(blank=True, related_name='days_week', to='business.dayweek')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('preco', models.FloatField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_name', to='business.company')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11, null=True)),
                ('birthday', models.DateField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.IntegerField(blank=True, choices=[(1, 'AC'), (2, 'AL'), (3, 'AP'), (4, 'AM'), (5, 'BA'), (6, 'CE'), (7, 'DF'), (8, 'ES'), (9, 'GO'), (10, 'MA'), (11, 'MS'), (12, 'MT'), (13, 'MG'), (14, 'PA'), (15, 'PB'), (16, 'PE'), (17, 'PI'), (18, 'PR'), (19, 'RJ'), (20, 'RN'), (21, 'RO'), (22, 'RR'), (23, 'RS'), (24, 'SC'), (25, 'SE'), (26, 'SP'), (27, 'TO')], default=27, null=True)),
                ('role', models.IntegerField(choices=[(1, 'Admin'), (2, 'Vendedor'), (3, 'Cliente'), (4, 'Entregador')], default=4)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('favorites', models.ManyToManyField(blank=True, related_name='favorites', to='business.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
